# Setup
title:               Diego Lopez Padilla
tagline:             'On technology, product development, etc.'
description:         'Learning for writing, writing for learning.'
#url:                 http://lanyon.getpoole.com
#baseurl:             ''
paginate:            5
permalink:           pretty
remote_theme:        poole/lanyon

# About/contact
author:
  name:              Diego Lopez Padilla
  url:               https://twitter.com/di_lopa
  email:             diegoloop@me.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
